---
title: "Recipes"
output: 
  html_document:
    toc: true
    toc_float: true 
---

# Cookies

### Chocolate Chip
**Ingredients**

* unsalted butter (100g)
* brown sugar (90g)
* granulated sugar (30g)
* egg (1) 
* vanilla extract or other flavor (2g)
* cake flour (100g)
* all purpose flour (100g)
* baking powder (2g)
* baking soda (1g)
* salt (1g)
* dark chocolate (140g)

**Instructions**

1. Warm butter to room temperature.
2. Cream butter and sugar with whisk or hand mixer. Add the sugar in 2 or 3 parts. The hand mixer works better than the whisk. 
3. Add flavorings.
4. Sift the dry ingredients into the wet ingredients. 
5. Fold the dry ingredients into the wet ingredients. Don't overmix! 
6. Add the chocolate and fold a few more times until the dough becomes thick. 
7. Refrigerate for 30 min. 
8. Shape dough into balls and press them down onto the baking sheet. 
9. Bake at 190$^\circ$C (374$^\circ$F) for 12 min.
10. Cool on a cooling rack.

### Brownie Cookies
**Ingredients** 

* unsalted butter (60g)
* dark chocolate (100g)
* egg (1)
* brown sugar (100g)
* plain flour (65g)
* cocoa powder (10g)
* baking powder (1/2t)
* salt (1/8t)

**Instructions** 

* Melt butter with chocolate over boiling water that's been taken off the stove. It's easier to melt if the butter is cut into small chunks and the chocolate is shaved. 
* Cream egg and brown sugar. Hand mixer instead of whisk gives a better result. 
* Combine melted chocolate and sugar/egg. 
* Sift dry ingredients into the wet. 
* Fold. 
* Spoon the batter on a baking sheet. An ice cream scooper works. Don't spoon too much batter or else the cookies will spill into each other. Makes 8-9 cookies.
* Bake in the oven for 12 min at 180$^\circ$C (356$^\circ$F). 

# Flour

### Noodles 
**Ingredients** 

* all purpose flour (250g)
* hot water (110g)
* 1/8 teaspoon salt
* 1/8 teaspoon baking soda

**Instructions** 

1. Heat water and mix in salt + baking soda. 
2. Cool the water until it's comfortable to touch. 
3. Mix the water into the flour slowly while stirring with a chopstick. It should create a shaggy dough. 
4. Form the dough into a ball. 
5. Rest dough for 30 min. 
6. Knead the dough.
7. Rest dough for a minimum of 30 min or up to 60 min. 
8. Repeat steps 6-8 until the dough is smooth. 
9. Dust the work surface with cornstarch and roll the dough into a thin circle. 
10. Fold the dough into an accordion and slice into thin pieces. Before slicing, dust cornstarch in between each fold. 

### Scallion Pancake 
**Ingredients**

* all purpose flour (400g)
* salt (2g)
* scallions

**Instructions** 

1. Add boiling water (83g) + room temperature water (167g) to the flour and knead until smooth.
2. Rest for 20 min.
3. Add 12g oil and knead.
4. Break off into chunks and roll them with salt and chopped scallions with oil. Roll and put on cast iron skillet with a cover. 400g of flour can break into 6 chunks. 

### Tortillas 
**Ingredients**

* flour (346g) 
* salt (1t)
* baking powder (1.5t)
* oil (33g)
* warm water (189 ml)

**Instructions**

1. Combine and rest 10 min.
2. Portion off 35g per piece (can make ~16 pieces)
3. Cook on a skillet but don't let it get too hot or else it will burn.

# Bread 

### Milkbread 
**Ingredients**

* all purpose flour (400g)
* sugar (12g or 1T)
* salt (1/8t)
* boiling water (83g)
* warm milk (167g)
* yeast (1t)
* 2 eggs
* oil (2T)

**Instructions**

1. Combine flour, sugar, salt, and water
2. Warm the milk and put yeast in. Note if using instant or active yeast. If active, bloom first. If instant, can go either in milk or directly in dry ingredients. Add into the mix. 
3. Add eggs. Save a little bit for egg wash at the end. 
4. Knead until combined and rest for 20 min. The dough is very wet. 
5. Add the oil and knead again until smooth. 
6. Rest for 1h. 
7. Flour your hands and the surface of the dough and push the air out. 
8. Split the dough into 3 parts or more depending on the size of the bread pan. 
9. Roll the dough into tubes and place into bread pan. 
10. Final proof for 1h. 
11. Put an egg wash over the surface. 
12. Bake at 375$^\circ$F for 30 min. 